export const CONSTANTS = {
    UPDATE_NAME: 'UPDATE_NAME',
    STARTING_DIFFICULTY: 'STARTING_DIFFICULTY',
    UPDATE_SCORE: 'UPDATE_SCORE',
    UPDATE_OPPONENT_SCORE: 'UPDATE_OPPONENT_SCORE',
    UPDATE_TIME: 'UPDATE_TIME',
    UPDATE_NUMBER_OF_QUESTIONS: 'UPDATE_NUMBER_OF_QUESTIONS',
    TOGGLE_LOADING: 'TOGGLE_LOADING',
    UPDATE_QUESTIONS_LIST: 'UPDATE_QUESTIONS_LIST',
    UPDATE_CURRENT_QUESTION_ID: 'UPDATE_CURRENT_QUESTION_ID',
    UPDATE_CURRENT_QUESTION: 'UPDATE_CURRENT_QUESTION',
    RESET: 'RESET'
}
